const ADD = "ADD";
const REMOVE = "REMOVE";
const REMOVE_ALL = "REMOVE_ALL";
const SELECT_ALL_SUB_CATEGORY = "SELECT_ALL_SUB_CATEGORY";
const REMOVE_ALL_SUB_CATEGORY = "REMOVE_ALL_SUB_CATEGORY";

export default {
  ADD,
  REMOVE,
  REMOVE_ALL,
  SELECT_ALL_SUB_CATEGORY,
  REMOVE_ALL_SUB_CATEGORY,
};
